package com.sueldosEmpresa.gui;

import com.sueldosEmpresa.dominio.Consultor;
import com.sueldosEmpresa.dominio.Empresa;
import com.sueldosEmpresa.dominio.TrabajadorFijo;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco J. Mulé <franjmule@gmail.com>
 */
public class JDCargarEmpleado extends javax.swing.JDialog {

    private final Empresa emp;

    /**
     * Creates new form JDCargarEmpleado
     *
     * @param parent
     * @param modal
     * @param emp
     */
    public JDCargarEmpleado(java.awt.Frame parent, boolean modal, Empresa emp) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.emp = emp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNombre = new javax.swing.JTextField();
        jtfLegajo = new javax.swing.JTextField();
        jtfFecha = new javax.swing.JTextField();
        jtfPuesto = new javax.swing.JTextField();
        jtfValorHora = new javax.swing.JTextField();
        jtfSueldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtfHorasExtra = new javax.swing.JTextField();
        jtfCantHoras = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jcbTipoEmpleado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cargar empleado");
        setResizable(false);

        jtfLegajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfLegajoKeyTyped(evt);
            }
        });

        jtfFecha.setText("dd/mm/yyyy");

        jtfValorHora.setEnabled(false);
        jtfValorHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfValorHoraKeyTyped(evt);
            }
        });

        jtfSueldo.setEnabled(false);
        jtfSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfSueldoKeyTyped(evt);
            }
        });

        jLabel5.setText("Nombre completo");

        jLabel6.setText("Nombre completo");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Legajo");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nombre completo");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Puesto");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Fecha de contratación");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Sueldo");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Horas extra");

        jtfHorasExtra.setEnabled(false);
        jtfHorasExtra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfHorasExtraKeyTyped(evt);
            }
        });

        jtfCantHoras.setEnabled(false);
        jtfCantHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCantHorasKeyTyped(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Cantidad de horas");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Valor por hora");

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jcbTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar tipo de empleado", "Consultor", "Trabajador Fijo" }));
        jcbTipoEmpleado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoEmpleadoItemStateChanged(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tipo de empleado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfCantHoras)
                                .addComponent(jtfValorHora)
                                .addComponent(jtfSueldo)
                                .addComponent(jtfPuesto)
                                .addComponent(jtfFecha)
                                .addComponent(jtfLegajo)
                                .addComponent(jtfHorasExtra)
                                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jLabel5)
                    .addContainerGap(234, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jLabel6)
                    .addContainerGap(224, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtfHorasExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCantHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbCancelar))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(194, 194, 194)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(258, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(204, 204, 204)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(248, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jcbTipoEmpleadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoEmpleadoItemStateChanged
        int tipo = jcbTipoEmpleado.getSelectedIndex();

        switch (tipo) {
            case 1: // consultor
                jtfCantHoras.setEnabled(true);
                jtfValorHora.setEnabled(true);
                jtfSueldo.setEnabled(false);
                jtfHorasExtra.setEnabled(false);
                break;
            case 2: // trabajador fijo
                jtfCantHoras.setEnabled(false);
                jtfValorHora.setEnabled(false);
                jtfSueldo.setEnabled(true);
                jtfHorasExtra.setEnabled(true);
                break;
            default:
                jtfCantHoras.setEnabled(false);
                jtfValorHora.setEnabled(false);
                jtfSueldo.setEnabled(false);
                jtfHorasExtra.setEnabled(false);
        }
    }//GEN-LAST:event_jcbTipoEmpleadoItemStateChanged

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        int tipo = jcbTipoEmpleado.getSelectedIndex();
        if (tipo != 1 && tipo != 2) {
            JOptionPane.showMessageDialog(this, "No se seleccionó tipo de empleado",
                    "Cargar empleado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nombre = jtfNombre.getText();
        String legajoSt = jtfLegajo.getText();
        String fecha = jtfFecha.getText();
        String puesto = jtfPuesto.getText();

        if (nombre.equals("") || legajoSt.equals("")
                || fecha.equals("") || puesto.equals("")) {
            mensajeCampos();
            return;
        }

        int legajo = Integer.parseInt(legajoSt);

        Date fechaInicio;
        if (validarFecha(fecha)) {
            fechaInicio = new Date(fecha);
        } else {
            JOptionPane.showMessageDialog(this, "La fecha debe estar en un formato dd/mm/yyyy", 
                    "Cargar empleado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        switch (tipo) {
            case 1:
                if (jtfValorHora.getText().equals("")
                        || jtfCantHoras.getText().equals("")) {
                    mensajeCampos();
                    return;
                }

                float valorHora = Float.parseFloat(jtfValorHora.getText());
                int cantHoras = Integer.parseInt(jtfCantHoras.getText());

                emp.agregarEmpleado(new Consultor(cantHoras, valorHora,
                        legajo, nombre, fechaInicio, puesto));

                break;
            case 2:
                if (jtfSueldo.getText().equals("")
                        || jtfHorasExtra.getText().equals("")) {
                    mensajeCampos();
                    return;
                }

                float sueldo = Float.parseFloat(jtfSueldo.getText());
                int horasExtra = Integer.parseInt(jtfHorasExtra.getText());

                emp.agregarEmpleado(new TrabajadorFijo(sueldo, horasExtra,
                        legajo, nombre, fechaInicio, puesto));

                break;
        }

        JOptionPane.showMessageDialog(this, "Empleado cargado con éxito");
        this.dispose();
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jtfLegajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfLegajoKeyTyped
        if (consumirTeclaInt(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfLegajoKeyTyped

    private void jtfSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfSueldoKeyTyped
        if (consumirTeclaFloat(evt.getKeyChar(), jtfSueldo.getText())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfSueldoKeyTyped

    private void jtfHorasExtraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfHorasExtraKeyTyped
        if (consumirTeclaInt(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfHorasExtraKeyTyped

    private void jtfValorHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorHoraKeyTyped
        if (consumirTeclaFloat(evt.getKeyChar(), jtfValorHora.getText())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfValorHoraKeyTyped

    private void jtfCantHorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCantHorasKeyTyped
        if (consumirTeclaInt(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfCantHorasKeyTyped

    private void mensajeCampos() {
        JOptionPane.showMessageDialog(this, "Faltan campos por completar",
                "Cargar empleado", JOptionPane.ERROR_MESSAGE);
    }

    private boolean consumirTeclaFloat(char key, String entrada) {
        boolean aux = false;
        if (!Character.isDigit(key)) {
            if (key == '.') {
                // boolean hayComa = false;

                for (int i = 0; i < entrada.length(); i++) {
                    if (entrada.charAt(i) == '.') {
                        aux = true;
                        break;
                    }
                }
            } else {
                aux = true;
            }
        }
        return aux;
    }

    private boolean consumirTeclaInt(char key) {
        boolean aux = false;
        if (!Character.isDigit(key)) {
            aux = true;
        }
        return aux;
    }

    private boolean validarFecha(String fecha) {
        boolean aux = true;
        try {
            Date date = new Date(fecha);
        } catch (Exception e) {
            aux = false;
        }
        return aux;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<String> jcbTipoEmpleado;
    private javax.swing.JTextField jtfCantHoras;
    private javax.swing.JTextField jtfFecha;
    private javax.swing.JTextField jtfHorasExtra;
    private javax.swing.JTextField jtfLegajo;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfPuesto;
    private javax.swing.JTextField jtfSueldo;
    private javax.swing.JTextField jtfValorHora;
    // End of variables declaration//GEN-END:variables
}
